app.config(function($routeProvider){
    $routeProvider
    .when('/' , {
        templateUrl:"views/home.html"
    })
    .when("/prod",{
        templateUrl:"views/product.html",
        controller:"productCtrl"
    })
    .when("/service",{
        templateUrl:"views/service.html"
    })
    .when("/contact",{
        templateUrl:"views/contact.html",
        controller:"contactCtrl"
    }) 
    .when("/indian",{
        templateUrl:"views/innerView/indian.html",
        controller:"myCtrl"
    })
    .when("/tamilnadu",{
        templateUrl:"views/innerView/tamilnadu.html",
        controller:"myCtrl"
    })
    .when("/ooty",{
        templateUrl:"views/innerView/ooty.html",
        controller:"myCtrl"
    })
    .when("/yelagiri",{
        templateUrl:"views/innerView/yelagiri.html",
        controller:"myCtrl"
    })
    .when("/yercaud",{
        templateUrl:"views/innerView/yercaud.html",
        controller:"myCtrl"
    })
    .when("/valparai",{
        templateUrl:"views/innerView/valparai.html",
        controller:"myCtrl"
    })
    .when("/tanjore",{
        templateUrl:"views/innerView/tanjore.html",
        controller:"myCtrl"
    })
    .when("/kanniyakumari",{
        templateUrl:"views/innerView/kanniyakumari.html",
        controller:"myCtrl"
    })
    .when("/hogenakkal",{
        templateUrl:"views/innerView/hogenakkal.html",
        controller:"myCtrl"
    })
    .otherwise({
        redirectTO:"/"
    });
})